### ISSUE TITLE
Install fails with "invalid serialized PackageId for key package.dependencies

### ISSUE THREAD

**Issue by StefanSchroeder** [bennofs/nix-index#134]
I followed the instructions in the README.

When running nix-env -if.

the command fails:
source root is nix-index
patching sources
installing
error: failed to sync

Caused by:
  failed to load pkg lockfile

Caused by:
  failed to parse lock file at: /build/nix-index/Cargo.lock

Caused by:
  invalid serialized PackageId for key `package.dependencies`
Traceback (most recent call last):
  File "/nix/store/nbc89g1i8z2m19g31gwkljrjb2kdp4gr-cargo-vendor-normalise/bin/.cargo-vendor-normalise-wrapped", line 42, in <module>
    main()
  File "/nix/store/nbc89g1i8z2m19g31gwkljrjb2kdp4gr-cargo-vendor-normalise/bin/.cargo-vendor-normalise-wrapped", line 17, in main
    assert list(data.keys()) == ["source"]
AssertionError
builder for '/nix/store/vvqpl2l85qnwyxkzlmk0d4zmdr7q3vri-nix-index-0.1.2-vendor.drv' failed with exit code 1
cannot build derivation '/nix/store/zvp5bh4xc91f6vy990ivvzsi9fmn16cq-nix-index-0.1.2.drv': 1 dependencies couldn't be built
error: build of '/nix/store/zvp5bh4xc91f6vy990ivvzsi9fmn16cq-nix-index-0.1.2.drv' failed

**Comment by bennofs** [comment]
Cannot reproduce on current master, so closing this.
