### ISSUE TITLE
thread 'main' panicked at 'slice index starts at 999935 but ends at 999934', src/database.rs:424:30

### ISSUE THREAD

**Issue by schuelermine** [bennofs/nix-index#205]
I ran the command `nix-locate --package xmonad-with-packages --regex ".*"`, and got the following backtrace:
```
thread 'main' panicked at 'slice index starts at 999935 but ends at 999934', src/database.rs:424:30
stack backtrace:
   0:     0x5642372c5202 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0b60020a4713e5fb
   1:     0x5642372f541c - core::fmt::write::hd2bbf674326f971d
   2:     0x5642372d4ed5 - std::io::Write::write_fmt::h9e09deb1651b82d4
   3:     0x5642372c4fc1 - std::sys_common::backtrace::print::hb0f6f2fe5c4496c1
   4:     0x5642372e0c4f - std::panicking::default_hook::{{closure}}::hf3d6d483953ab294
   5:     0x5642372e08d4 - std::panicking::default_hook::h7229a04a9f746202
   6:     0x5642372e1289 - std::panicking::rust_panic_with_hook::h7c53bfc9ab300aca
   7:     0x5642372c5557 - std::panicking::begin_panic_handler::{{closure}}::hc2a71b5a463ec201
   8:     0x5642372c5334 - std::sys_common::backtrace::__rust_end_short_backtrace::he21bec3aa77e6ef6
   9:     0x5642372e0e02 - rust_begin_unwind
  10:     0x564237119563 - core::panicking::panic_fmt::h136a2a3f69fc0251
  11:     0x5642372f25d2 - core::slice::index::slice_index_order_fail_rt::h7342d3a492917d85
  12:     0x5642371197a7 - core::slice::index::slice_index_order_fail::h25c1afcf85efe520
  13:     0x56423713dea0 - <nix_index::database::ReaderIter as core::iter::traits::iterator::Iterator>::next::h21d6d6c74b7cc0b0
  14:     0x56423712a683 - nix_locate::main::hb25d903e1b6b73b7
  15:     0x564237120683 - std::sys_common::backtrace::__rust_begin_short_backtrace::h32a044713ec80151
  16:     0x564237124a79 - std::rt::lang_start::{{closure}}::h6e4a2473b22a4cbd
  17:     0x5642372d3d84 - std::rt::lang_start_internal::h398023bd7970a80b
  18:     0x5642371312bb - main
  19:     0x7f357f62924e - __libc_start_call_main
  20:     0x7f357f629309 - __libc_start_main_alias_1
  21:     0x564237119905 - _start
  22:                0x0 - <unknown>
```

**Comment by bennofs** [comment]
Can you share your nix-index database? (Should be in `~/.cache/nix-index` by default)

**Comment by schuelermine** [comment]
https://nextcloud05.webo.cloud/s/7i6tpJMDiSM6zqD
Password: `|4aI9,rE:#`
